version: '3'

tasks:
  run:
    cmds:
      - reflex -r '\.go$' -s go run $(ls *.go) $*

  build:
    cmds:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags lambda.norpc -o bootstrap $(ls *.go)

  deploy:
    deps:
      - build
    cmds:
      - lambroll deploy --envfile .envrc

  clean:
    cmds:
      - rm -f bootstrap

  logs:
    cmds:
      - lambroll logs --follow
